export const SEARCH_ART_VALUE = "SEARCH_ART_VALUE"

export const ART_LIBRARY_REQUEST = "ART_LIBRARY_REQUEST"
export const ART_LIBRARY_SUCCESS = "ART_LIBRARY_SUCCESS"
export const ART_LIBRARY_FAILURE = "ART_LIBRARY_FAILURE"